### ISSUE TITLE
Issues over mobile hotspot

### ISSUE THREAD

**Issue by eeldivad** [NHAS/wag#119]
I'm having issues with WAG VPN over mobile hotspot.  I'm using Google Fi hotspot on my Pixel phone.  Everything works fine over my WIFI networks.  

When I connect using my mobile hotspot then this is what I can/can't do:
- I can 
    - ping my WAG server on the private IP
    - telnet to the listening port for the MFA page on the WAG server
- I can't 
    - access the MFA page

So I turned off MFA and tested again.  Now I can ping IPs on the network and telnet to port 22 to get a response.  But I can't SSH to the servers even though port 22 is open and responds.

Everything works fine if I switched back to my home Wifi and not using the mobile hotspot.  Anyone have any ideas?  I read somewhere that it could be the MTU settings but I tried a few different MTU and nothing works.

With my mobile hotspot, it does work when I connect to a different Wireguard VPN server (not WAG).  Is WAG using an old version of Wireguard or something different?

**Comment by NHAS** [comment]
Hi there, do you have any wag logs you could share?

Also, when you say you can telnet to the listening port, what does that mean? As in you can connect to the port, or you're talking to it with raw HTTP?

Also what version are you on. 


Just a side node, your mobile data is most likely behind a CGNAT which can cause wag to be a bit sad due to how it tracks the users endpoint. However that should never stop you from being able to connect to the MFA page.

**Comment by NHAS** [comment]
Hi there as there isn't any more information on this. I am going to close this issue

**Comment by eeldivad** [comment]
turned out to be an issue with my phone.  i had the pixel 6.  i just got a pixel 8 and it works fine.  thanks
