### ISSUE TITLE
Upgrade Version Guide

### ISSUE THREAD

**Issue by codechirag123** [NHAS/wag#123]
Hi, thanks for the amazing product which enhances secured access. 
Can you please provide a user guide to upgrade the wag version to a newer release.
I hope that there should not be any downtime while performing the version upgrade and the possibility to version upgrade from any version to any version.

Also is it possible to deploy it in Kubernetes?

**Comment by NHAS** [comment]
Hi there. 

Wag should automatically upgrade any data to the latest version on first run.

You will have to restart your wag instance to do this, and thus there will be downtime. 

As I do not use kubernetes I haven't made a deployment for kubernetes. 

Unfortunately due to the nature of your request, which falls under support rather than bug fix or feature request, you would have to donate to the project for me to write a detailed guide for you. 
As I do not have the time to field all support requests otherwise. 

Thanks!

**Comment by codechirag123** [comment]
Hi @NHAS I restarted my wag server also restarted the service with version v2.0.3 (old)
The current version still shows v2.0.3
![image](https://github.com/NHAS/wag/assets/134513193/5e013d53-8928-4c93-829b-932de940ba70)
