### ISSUE TITLE
feat req: Interactive config generator

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/wag#18]
It would be nice for Wag to have a CLI command to generate a configuration file interactively.

For example
```
What is the public address your devices will connect to? 1.2.3.4:4321
What help email would you like displayed on the auth page? bob@example.com
.. etc ..
```

**Comment by paulb-opusvl** [comment]
Initially, I thought the same. I would be nice to regenerate a config file at any point. Then I realised that the only point at which the user private key is available is at the point of registration. Once they collect the config during the registration process, it's gone from the server.

This makes sense as it keeps the keys separate and prevents even admins from having access to both of the users keys.

That said, I carry out the user registrations and send the users the config myself. I have a repository of keys (but not on the wag server). I also modify the config to user /24 addresses in the `AllowedIps=` rather than lots of individual IP's. That way, I can update an ACL to add a user to allow them access to another system without them having to edit their config.

**Comment by NHAS** [comment]
Hi @paulb-opusvl, 
This issue is specifically opened for generating the server side config rather than the results of the client registration.

Little bit confused by what you mean about modifying the client config to use a /24, you should be able to do this in the `Acls` section by `Allow`-ing or `Mfa`-ing a subnet such as:

```json
 "group:nerds": {
                "Mfa": [
                    "192.168.3.0/24"
                ],
                "Allow": [
                    "192.168.3.5/32"
                ]
            },
```

Which would allow access to the `192.168.3.0/24` network when Mfa'd. I.e hopefully you can just use the registration process to do that for you, so no manual editing required! 
  

To tangent off this tangent, I've been thinking about your request for centralised management of wag, what does that look like in your dream world?

**Comment by paulb-opusvl** [comment]
My bad, I should learn to read without diving in.

I have lots of acls that have only /32, and I don't want all clients to access everything. If I put /24 in the `AllowedIPs=` I don't have to change it if I add another /32 in the ACL. The client will already have the route, but not the access - until I add them to the ACL.

A management GUI would be very nice. We have relatively few users and their configs can be managed with Ansible. I'm not necessarily uncomfortable with `.json`, but others would benefit from having a simple management interface.
