### ISSUE TITLE
Feature request: support authentication using an oauth2 client

### ISSUE THREAD

**Issue by olekristoffer** [NHAS/wag#19]
Hi

Thank you for a great project, it is really useful.

Would it be possible for to extend wag to support user authentication using OpenID Connect / oauth 2.0 protocol? This would add the benefit of both simplifying the user managment and allow for a rich set of MFA solutions in addtion to supporting single sign-on from different providers. Authentication could be implemented using locally hosted services, e.g. by using implementations such as keycloak, or provided by trusted third parties for example google or github?

https://github.com/coreos/go-oidc
https://pkg.go.dev/golang.org/x/oauth2#section-readme

examples:
https://fusionauth.io/blog/2020/10/22/securing-a-golang-app-with-oauth
https://medium.com/@pliutau/getting-started-with-oauth2-in-go-2c9fae55d187

**Comment by NHAS** [comment]
Hi there @olekristoffer,

I think this is a great idea! However I cant promise it any time soon as it would require a substantial amount of work to reorganize how I manage user identities (which Im planning on doing as I want this to be easier to manage). 

So yes! Hopefully! Maybe! Soon :P

**Comment by paulb-opusvl** [comment]
Would be a big change. A move from device based auth to user based auth, or a combination of the two.

Right now I like its relative simplicity.

**Comment by NHAS** [comment]
Well, one step closer to this now as the most recent version separates device from user.

**Comment by NHAS** [comment]
Wag now has webauthn, and the changes I've made to facilitate that have made adding this almost trivial, so I'll be looking in to adding this real soon. 

My main concern with this change is that you'll still have to define your policies for what authorised users can access in the wag configuration file itself. 
So it'd be rather split in terms of management, users could be managed with <insert your identity provider here> but the actual route access wouldnt be

**Comment by NHAS** [comment]
My current plan of attack is to use OIDC with a groups claim where the groups will match with the polices defined in the `config.json` this means that all management will be able to be done centrally for the most part, bar tweaking the access policies. 

Unfortunately this will not support googles IdP as for some reason they dont support the group claims that other identity providers do, so its not possible to map user groups to oidc assertion (and Im not writing a special case just for google)

**Comment by paulb-opusvl** [comment]
Nice. We use Keycloak for OAuth/IdP so having this support would be awesome. It moves all our authentication into a common mechanism and makes the use of existing groups really useful.

Looking forward to this.

**Comment by NHAS** [comment]
Ha! Well good, ironically I'm using keycloak to test my first versions!

**Comment by NHAS** [comment]
Hm, unfortunately while adding oidc as an authentication method is trivial, having the groups be able to change for a user on demand is less so, might take a bit longer than I thought.

**Comment by NHAS** [comment]
@olekristoffer this feature now exists in its beta form here: https://github.com/NHAS/wag/releases/tag/v3.1.0-pre-release

Currently all this allows users to do is authorise with the identity provider, and will mean that users will still need policies, groups and devices created and registered with wag directly. 

Im planning on using the OIDC claims to do groups automatically in the future, so only group policy and device registration will be handled on the wag server itself. 

Hope this works for you!

As usual, please provide any UI/UX feedack :)

**Comment by NHAS** [comment]
Sweet this feature is now fully completely, the OIDC IdP can now manage what groups a user is in on the wag side, without wag ever having to directly know about the user. 

As this was a huge change, Im still going to leave it in pre-release for a bit until someone tests it. 

But it can be found here: https://github.com/NHAS/wag/releases/tag/v3.2.0-pre-release

For completeness (and since I havent written up the docs in a sensible place yet) here are some instructions on running it with keycloak. 

config.json policies:
```json
"Policies": {
            "*": {
                "Mfa": ["1.1.1.1"],
                "Allow": [
                    "google.com"
                ]
            },
            "group:nerds": {
                "Mfa": [
                    "192.168.3.4/32"
                ],
                "Allow": [
                    "192.168.3.5/32"
                ]
            },
            "group:administrators": {
                "Mfa": [
                    "8.8.8.8"
                ]
            }
        }
```

After setting up your realm in keycloak create groups (note the `group:` prefix):
![image](https://user-images.githubusercontent.com/6820641/209415799-3ba00168-0837-4d18-a89d-2adfc86832cb.png)
  
Create a client (i just used the default `account`):
![image](https://user-images.githubusercontent.com/6820641/209415859-e425ef7e-d2e9-45c6-9b72-2e78c7d1b9f1.png)

Click on `account`  

In `Settings`: 

1. enable `Client Authentication`, `Authorisation`, `Standard Flow` and `Direct Access grants` like so:
![image](https://user-images.githubusercontent.com/6820641/209415938-de83d672-29b7-4802-88b4-03e19321759b.png)

2. Set your valid redirect URLS to your vpn domain with `/authorise/oidc` as the direction, also add `+` in web origins.
![image](https://user-images.githubusercontent.com/6820641/209416021-1f4857d3-a643-4f62-a664-4b08bda99452.png)


Add your credentials from `Credentials` to the wag config file `Authenticators.OIDC.ClientID/ClientSecret`

In `Client scopes`:
1.  Click on the dedicated scope
![image](https://user-images.githubusercontent.com/6820641/209416086-ec158274-de4c-4acc-af71-df51057779b1.png)

2. Add a mapper by configuration
![image](https://user-images.githubusercontent.com/6820641/209416093-b57be60e-b32d-491e-ba4d-f7a7e5850068.png)

3. Choose `Group Membership`
![image](https://user-images.githubusercontent.com/6820641/209416104-84fd9407-5ba4-4444-acd6-a0fc5bb3e50b.png)

4. Set `Name` and `Token Claim Name` to `groups` (or whatever group name you want, just update it in the wag config file if its not groups). And disable `Full group path`
  
![image](https://user-images.githubusercontent.com/6820641/209416190-eca37611-e52a-484b-89f3-3d8e9e896619.png)


  
  
Then from here, add your users as you usually would, you can also disable other authentication methods in wag. But this message is long enough. 

Hope someone plays with it!

**Comment by NHAS** [comment]
Now on main branch so this issue will be closed :)

**Comment by paulb-opusvl** [comment]
I'd like to reopen this, only so I can understand how it is supposed to work. More than a little excited about the prospect of mapping groups to our domain.

The oidc part in keycloak, no problem. But I'm not sure what I'm to expect as a user when I try to logon. Am I supposed to get a redirect to the `OIDC.IssuerURL` and be returned on successful authentication?

I'm not getting anywhere.

```json
    "Authenticators": {                                                          
        "Issuer": "otp-uat.domain.tld",                                      
        "DomainURL": "https://otp-uat.domain.tld",                               
        "DefaultMethod": "oidc",                                             
        "Methods": [                                                             
            "totp",                                                          
            "oidc"                                                               
        ],                                                                   
        "OIDC": {                                                            
            "IssuerURL": "https://sso.domain.tld/auth/realms/opusvl",    
            "ClientSecret": "SecretKey",              
            "ClientID": "wag-uat",                                       
            "GroupsClaimName": "groups"                                      
        }                                                                
    }, 
```

I even tried removing the `totp` entry. I just get the same MFA behaviour.

**Comment by paulb-opusvl** [comment]
I think I'm onto something

```sql
		SELECT 
			mfa_type 
		FROM 
			Users
		WHERE
			username = ?
```

I don't have a column mfa_type in my sqlite.

```sql
sqlite> .schema Devices
CREATE TABLE Devices(address string primary key, username string not null, publickey string not null unique, endpoint string, attempts integer DEFAULT 0 not null, preshared_key TEXT DEFAULT "unset" NOT NULL);
```

Have I missed something in building? Like a migration hasn't run?

**Comment by paulb-opusvl** [comment]
I'm missing the bit about 'mfa_type' in 'Users'.

Updated my record with `mfa_type` of 'oidc` and now I get a redirect to auth. I just need to resolve the redirect now.

**Comment by NHAS** [comment]
Effectively a user has an MFA method that gets set in the sqlite3 database (which you've seen). 

If their `mfa_type` is already set then they'll continue to use the previous MFA method of their choice, so we dont accidentally lock users out if we suddenly add methods. 
You should use  `wag users -reset-mfa -username <your.username.here>` command to reset their MFA. This will then prompt them on next usage to select a method of MFA which should do the rest for you. 

Other than that your configuration file looks correct. If resetting the users mfa doesnt work, try creating a new user (and give me the logs of what happens and I'll sort it out).

**Comment by paulb-opusvl** [comment]
Wowsers, just got this working on my UAT system, and have to say - well done.

**Comment by NHAS** [comment]
Awesome!

Really glad to hear it's all working for you. This was an especially big piece of work and pretty fun to build.

Tell me how it goes or if you find any issues with it.

But for now since you've confirmed its working and it's released to the world I'm going to mark this as closed.

**Comment by paulb-opusvl** [comment]
I may be a bit premature.

The SSO auth works just fine. I sign in and see in the console the groups that it pulls from the claim.

I thought I would then be able to create Policies that match the groups, and not have any Group section in `config.json` as the groups and membership come from the claim. All I needed to do was add the policy for that group. But I even added in an empty group to test.

```json
"Acls": {
  "Policies": {
    "group:access-role-people": {
        "MFA": [
          "10.0.0.1/32",
          "10.0.0.2/32"
        ]
    }
  }
````

But when I attempt to access something in the group, I get nowhere. If I look at the firewall I also don't see any "Mfa" rules against my device.

```text
2023/03/02 20:46:05 paul.b 192.168.254.28 used sso to login with groups:  [access-files-developer access-role-people ... ]
```

```json
  "paul.b": {
    "LastPacketTimestamp": 0,
    "Expiry": 0,
    "MFA": null,
    "Public": [
      "10.0.6.254/32",
      "192.168.254.1/32"
    ],
    "Devices": [
      {
        "IP": "192.168.254.28",
        "Authorized": true
      },
      {
        "IP": "192.168.254.27",
        "Authorized": false
      },
      {
        "IP": "192.168.254.3",
        "Authorized": false
      }
    ]
  },
```

**Comment by NHAS** [comment]
Ah this is one of those times where the devil is in the detail. You need to make your groups be prefixed with the wag `group:` prefix. 

So the log should look like: 
```
2023/03/02 20:46:05 paul.b 192.168.254.28 used sso to login with groups:  [group:access-files-developer group:access-role-people ... ]
```

**Comment by NHAS** [comment]
That's a valid point. More than happy to change it, very easy to change.

**Comment by paulb-opusvl** [comment]
PS. If you would like some assistance with documentation, I have been given the go ahead to spend some time to assist.

**Comment by NHAS** [comment]
The real blocker for documentation at the moment is the fact I have to create a website for it frankly. I dont mind writing it once I've got a little thing set up, I've just currently got 0 motivation to actually make the site (going to be statically generated using [hugo](https://gohugo.io/) with the [docsy](https://themes.gohugo.io/themes/docsy/) theme unless I find something better). 

But when I am going to make it, I'll add you to the repo to write up things if you want!

**Comment by NHAS** [comment]
@paulb-opusvl Howdy, I've added you to the docs page I've made. Feel free to put whatever you want in there, I'll be getting a proper domain for it soon, then adding it to the wag main page.

**Comment by paulb-opusvl** [comment]
For documentation, I was expecting a readthedocs or github pages, both would require me to learn how.

Back on oauth2 and groups. Upgraded to 4.1.1.1 and it works, as long as you understand what's expected. The oauth group claim contains groups that are NOT prefixed with `group:`. To manage their ACL you use them as you would a user, eg. no `group:` prefix.

```json
            "access-role-projectmanagement": {
                "Mfa": [
                    "10.0.6.125/32",
                    "10.0.4.125/32"
                ]
            },
```
This seems a little strange, especially when you get to the management UI which I'm loving. As you can't manage these as groups, as the UI expects the prefix. So you manage the rule as if a user.

[Screenshot](https://imgur.com/a/KINGrVG)

When you logon as an oauth2 user you wont see anything in the groups to indicate what you are a member of, but looking at the user you will see all of your oauth2 groups. Also the UI Diagnostics, Firewall State will show you the rules are getting applied.

**Comment by NHAS** [comment]
On the docs side of things:
The repo is github pages but uses Hugo instead of readthedocs. So a simple commit will be built and displayed on the page (ill add a link to the page in that repos read me).

For writing your own docs, have a look in the content folder and make sure it works by using the local build first, which I have instructions for in the read me.


On the oaith2 side of things:
I'm a little bit confused what you mean with the groups having to be as if they're a single user.
The way I've changed groups in the code to be handled without the `group:` prefix from the idp side of things is that when parsing the token claims it just adds the `group:` prefix so I'm not sure why that's not mapping to regular groups for you.

Also, is it important a user knows what groups they're part of? As I can add that to the /status page and/or the authorisation confirmation page

**Comment by NHAS** [comment]
Yeah Im not sure what you mean. So in my setup, I have a `test_user` assigned to a group in keycloak:

![image](https://user-images.githubusercontent.com/6820641/224113249-19acf965-1d8e-4073-8284-a5148b5cfd47.png)

In wag I have a rule relating to the group, `group:toast`

![image](https://user-images.githubusercontent.com/6820641/224113111-1c88f03f-98c3-46c3-8c0b-ad261c173323.png)

Rules for the toast group:
![image](https://user-images.githubusercontent.com/6820641/224113358-4ed657ef-0d83-4c59-8d05-2ccb928622ba.png)


And after that user has logged in with the IdP then we get these routes:

```json
$ curl http://vpn.test:8081/status/  | jq
  "IsAuthorised": true,
  "Routes": [
    "4.4.4.4/32",
    "5.5.5.5/32",
    "142.250.67.14/32",
    "1.1.1.1/32",
    "10.123.5.1/32"
  ]
}
```

**Comment by NHAS** [comment]
Docs for this: https://nhas.github.io/wag-vpn.github.io/docs/guides/single_sign_on_with_keycloak/

Check out the management section :)
