### ISSUE TITLE
ManagementUI over TLS

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#30]
Even with `Certpath` and `KeyPath` management UI runs without TLS.

```json
    "ManagementUI": {
        "ListenAddress": "10.0.0.78:8443",
        "Enabled": true,
        "CertPath": "/etc/letsencrypt/live/domain.tld/fullchain.pem",
        "KeyPath": "/etc/letsencrypt/live/domain.tld/privkey.pem"
    },
```

## Evidence

```shell
$ curl https://10.0.0.78:8443
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

$ curl http://10.0.0.78:8443 
<a href="/login">Temporary Redirect</a>.
```

PS. Nice job on the web gui :+1:

**Comment by NHAS** [comment]
Ah yes. I did just totally overlook this because in my mind the web UI should only ever be accessed via SSH port forward or something similar. 
As it doesnt support MFA (yes, I know, its mainly pulling the code up to here is more difficult and couples things in a gross way currently). 

I will however add this because it makes sense.

**Comment by NHAS** [comment]
This is now on the unstable branch :)
