### ISSUE TITLE
OIDC issue

### ISSUE THREAD

**Issue by Cody7172** [NHAS/wag#53]
I have a second problem, I tried to set up oidc
I added an oidc to Authenticators Methods, received data from Google API and wrote down the necessary:
```
"DomainURL": "https://my domain",
         "OIDC": {
             "IssuerURL": "https://accounts.google.com",
             "ClientSecret": "secret",
             "ClientID": "client ID",
             "GroupsClaimName": "groups"
```
In the Google management console, I specified Authorized redirect URIs for my domain (https://mydomain/authorise/oidc)
Also in the config I specified "accounts.google.com" in the allow section so that it would be available during the mfa

But when i choose SSO and choose my google account, then I get
https://*mydomain*/authorise/oidc?state=*some key*
ERR_CONNECTION_REFUSED

Could you please tell me what I'm doing wrong?
I also read a lot of documents about oidc but I can't understand what is the problem here

**Comment by NHAS** [comment]
As I have only used hashicorp vault myself I cant really speak to what google does. Unfortunately this is probably a configuration issue on that side of things. 

This is kind of bordering into "provide support" rather than detailing issues or feature requests for Wag. 

While I love helping and supporting people that use Wag this can be a bit of a drain on my time and I am looking into options for providing paid support for setup and deployment issues. 

Until that becomes a direct option if you wanted to donate I'd be more than happy to do an entire setup with a Google account on my side of things then give you a detailed step by step guide.

**Comment by Cody7172** [comment]
I got it, thanks a lot for the help anyway!
