### ISSUE TITLE
Proxy for the tunnel webserver - MFA portal

### ISSUE THREAD

**Issue by Vinc89** [NHAS/wag#80]
Hello,

I would like to ask if it's possible to setup a proxy for the tunnel webserver where the MFA authentication takes place.
It would be nice to have HTTPS and DNS to not type the IP and port.

my config.json is with proxy true
```
   "Proxied": true,
    "ExposePorts": [
      "80/tcp",
      "443/tcp",
      "8080/tcp"
     ],



        "Tunnel": {
            "Port": "4443"
        }

```
I tried a simple apache proxy

```
ProxyPass /    http://192.168.22.1:4443/
ProxyPassReverse / http://192.168.22.1:4443/
```

But I get a 400 Bad request.

I'm running the latest binary
```
curl -L $(curl -s https://api.github.com/repos/NHAS/wag/releases/latest | jq -M -r '.assets[0].browser_download_url') -o wag
```

**Comment by NHAS** [comment]
I can indeed confirm that it is possible to use a reverse proxy for wag. Unfortunately this definitely falls under "support" rather than "bug or feature request". 

As I dont have unlimited time Im not in the position to do support issues without payment. But I can definitely confirm that there are working configurations! 

Good luck!
