### ISSUE TITLE
Version returns UNKNOWN

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#9]
After upgrading/pulling the latest version, when using the version option, it returns `UNKNOWN`

```shell
$ sudo ./wag version                   
UNKNOWN
```

Other than that, it appears to behave as previously.

**Comment by NHAS** [comment]
Is this from the releases page or self building? 

If you self build you need to now build with the makefile (`make`)

**Comment by paulb-opusvl** [comment]
Self building.

And why are you so quick to respond? :)

I'm totally loving this project. We're just rolling it out after initial tests, and the testers like how simple it is. Which is important to me, as not all of our users are infrastructure savvy. A simple connect and visit a web page is just perfect.

**Comment by NHAS** [comment]
Yeah with self building you'll need to use the make file, otherwise it wont inject the current git tag. 

I think our timezones just match up rather well, I tend to be online whenever you ask questions haha. 

Yeah I just did my roll out for work actually! Out of interest, how did you guys roll it out? I was using jamf + brew which... gotta say not fond of brew very much. 

Have you had any roll out problems as of yet? And also I am looking to centralise the management of things, just havent thought of a good way to do it as of yet.

**Comment by paulb-opusvl** [comment]
Perfect.

```shell
$ sudo ./wag version
v1.1.1
```

We're on a manual roll-out to existing staff, we don't have many, so it's pretty simple. New builds will get added with ansible.

One of our perl devs already piped up with sounds like you need a management interface, but really we're so small it's not an issue. I have some problematic users that I'm including just now, so the story continues :D

Keep up the great work.

**Comment by NHAS** [comment]
Ironically I am planning on writing a wee little web interface as a separate project that just hooks into the unix socket that wag opens.  
We shall see if that ever becomes something tho, as Im not a huge fan of web dev :P

**Comment by NHAS** [comment]
As usual, if you have any feature requests or improvements you know where to find me
